#!/usr/bin/env bash

start(){
    ssh -D 8123 -f -C -q -N $1 && echo "socks is runing"
    # set socks setting in System settings > Network > network proxy 
    gsettings set org.gnome.system.proxy mode 'manual'
    gsettings set org.gnome.system.proxy.socks port 8123
    gsettings set org.gnome.system.proxy.socks host 'localhost'
    gsettings set org.gnome.system.proxy ignore-hosts "['localhost', '127.0.0.0/8', '::1']"
    
    all_proxy=socks://localhost:8123/
}

stop(){
    gsettings set org.gnome.system.proxy mode 'auto'
    pkill --full 'ssh -D' 

    unset all_proxy
    unset socks_proxy
    unset ALL_PROXY
}

status(){
    pgrep --full "ssh -D" >/dev/null && echo 'Running...' || echo 'Stoped'
}

help(){
    echo "Usage: $0 COMMAND [USER@SERVER]"
    echo "Commands:"
    echo "  sta user@server  Runs proxy on server by user."  
    echo "  stop             Stops proxy."
    echo "  -h, --help       Shows this message."
    echo ""
}

case $1 in
    "start")
        start $2;;
    "status")
        status ;;
    "stop")
        stop ;;
    "-h"|"--help")
        help ;;
    "")
        echo ""
        echo "No option is provided please use one of available options."
        echo ""
        help
        exit 1 ;;
    *)
        echo ""
        echo "Invalid command is provided please use one of available command."
        echo ""
        help
        exit 1 ;;
esac

# ALL_PROXY=socks://localhost:8123/
# no_proxy=localhost,127.0.0.0/8,::1
# NO_PROXY=localhost,127.0.0.0/8,::1
# socks_proxy=socks://localhost:8123/
